include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    exclude:
      - "**.freezed.dart"
      - "**.g.dart"
      - "**/generated_plugin_registrant.dart"
