name: snookerpad
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
  build_runner: ^2.2.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_pdfview: ^1.2.5
  fluttertoast: ^8.1.2
  freezed: ^2.1.0+1
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.0.0
  image_picker: ^0.8.5+3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  localization: ^2.1.0
  lottie: ^1.4.3
  path_provider: ^2.0.11
  rolling_switch: ^0.0.2
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  wheel_chooser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/rules/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/red.png"

flutter_native_splash:
  color: "#283b31"
  image: assets/images/logo2.png
  fullscreen: true
  android_12:
    color: "#283b31"
    icon_background_color: "#283b31"
