name: snookerpad
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.5+3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  localization: ^2.1.0
  lottie: ^1.4.3
  path_provider: ^2.0.11
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  wheel_chooser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
